import { RichText } from '@wordpress/block-editor';
import { Button } from '@wordpress/components';
import EditableImage from '../../components/EditableImage';

export default function ProductPage( { product, index, products, onChange, onAdd, onBack } ) {
	if ( ! product ) return null;
	const update = ( patch ) => onChange( products.map( ( item, itemIndex ) => itemIndex === index ? { ...item, ...patch } : item ) );
	return <><section className="perfumes-breadcrumb">Inicio / Perfumes / { product.brand } / { product.name }</section><section className="perfumes-product-detail"><div className="perfumes-product-detail__gallery"><EditableImage className="perfumes-product-detail__image" imageUrl={ product.imageUrl } label="Imagen principal" onChange={ ( imageUrl ) => update( { imageUrl } ) } /></div><div className="perfumes-product-detail__info"><RichText tagName="p" className="perfumes-product-card__brand" value={ product.brand } onChange={ ( brand ) => update( { brand } ) } /><RichText tagName="h1" value={ product.name } onChange={ ( name ) => update( { name } ) } /><p className="perfumes-product-detail__rating">4.9 · 128 reseñas · <strong>{ product.stock ? 'En stock' : 'Agotado' }</strong></p><div className="perfumes-product-detail__price"><RichText tagName="strong" value={ product.price } onChange={ ( price ) => update( { price } ) } /><RichText tagName="del" value={ product.oldPrice } onChange={ ( oldPrice ) => update( { oldPrice } ) } /></div><RichText tagName="p" className="perfumes-product-detail__description" value={ product.description } onChange={ ( description ) => update( { description } ) } /><div className="perfumes-product-detail__actions"><Button variant="primary" onClick={ () => onAdd( index ) }>Agregar al carrito</Button><Button variant="secondary" onClick={ onBack }>Seguir comprando</Button></div><div className="perfumes-detail-benefits"><span>Original y sellado</span><span>Certificado de garantia</span><span>Envio asegurado</span></div></div></section></>;
}
