import { Button } from '@wordpress/components';
const numberFromPrice = ( value ) => Number( String( value || '' ).replace( /[^0-9]/g, '' ) );
const priceLabel = ( value ) => `$ ${ value.toLocaleString( 'es-CO' ) }`;
export default function CartPage( { products, cart, setCart, onBack } ) {
	const lines = Object.entries( cart ).map( ( [ index, quantity ] ) => ( { product: products[ Number( index ) ], index: Number( index ), quantity } ) ).filter( ( line ) => line.product && line.quantity > 0 );
	const subtotal = lines.reduce( ( total, line ) => total + numberFromPrice( line.product.price ) * line.quantity, 0 );
	const changeQuantity = ( index, amount ) => setCart( { ...cart, [ index ]: Math.max( 0, ( cart[ index ] || 0 ) + amount ) } );
	return <><section className="perfumes-page-band perfumes-page-band--center"><p>Inicio / Carrito</p><h1>Tu carrito de compras</h1><span>{ lines.length } productos · Reserva tus fragancias, el stock se libera en 30 minutos</span></section><section className="perfumes-cart-page"><div className="perfumes-cart-list">{ lines.length ? lines.map( ( line ) => <article key={ line.index } className="perfumes-cart-line"><div className="perfumes-cart-line__image">{ line.product.imageUrl && <img src={ line.product.imageUrl } alt="" /> }</div><div><strong>{ line.product.brand }</strong><h3>{ line.product.name }</h3><span>{ line.product.size }</span></div><div className="perfumes-quantity"><Button onClick={ () => changeQuantity( line.index, -1 ) }>-</Button><span>{ line.quantity }</span><Button onClick={ () => changeQuantity( line.index, 1 ) }>+</Button></div><strong>{ priceLabel( numberFromPrice( line.product.price ) * line.quantity ) }</strong><Button isDestructive onClick={ () => setCart( { ...cart, [ line.index ]: 0 } ) }>Eliminar</Button></article> ) : <div className="perfumes-cart-empty"><h2>Tu carrito esta vacio</h2><Button variant="primary" onClick={ onBack }>Ver catalogo</Button></div> }</div><aside className="perfumes-order-summary"><h2>Resumen de compra</h2><div><span>Subtotal</span><strong>{ priceLabel( subtotal ) }</strong></div><div><span>Envio</span><strong>Gratis</strong></div><div className="perfumes-order-summary__total"><span>Total</span><strong>{ priceLabel( subtotal ) }</strong></div><Button variant="primary" disabled={ ! lines.length }>Finalizar compra</Button><small>El checkout se conecta a WooCommerce al activar la integracion.</small></aside></section></>;
}
